export const FETCH_BANNER              = 'FETCH_BANNER';
export const FETCH_PRODUCT             = 'FETCH_PRODUCT';
export const FETCH_PRODUCT_FEATURED    = 'FETCH_PRODUCT_FEATURED';
export const FETCH_PRODUCT_LATEST      = 'FETCH_PRODUCT_LATEST';
export const FETCH_PRODUCT_VIEWED      = 'FETCH_PRODUCT_VIEWED';